name: Python Build
on:
  pull_request:

jobs:
  tsc:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install python 3.10.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6
    - name: install dependencies
      run: python -m pip install --upgrade pip
    - name: run unit tests
      run: python3 -m unittest -v